---
title: "Soft Power for D data set"
author: "Ruben Sancho, Bruno Contreras Moreira"
output:
  html_document: default
  pdf_document: default
---

```{r knitr setup, include=FALSE,  eval=TRUE, echo=FALSE, warning=FALSE}
library(knitr)
knitr::opts_chunk$set(eval=TRUE, cache=FALSE, message=FALSE, warning=FALSE,
                      comment = "")
```


```{r data}

# Display the current working directory
getwd();
workingDir = ".";
setwd(workingDir);


library(WGCNA);
options(stringsAsFactors = FALSE);
allowWGCNAThreads();

load(file = "datExpr.RData")
```


```{r unsigned}

# Choose a set of soft-thresholding powers

powers = c(c(1:12), seq(from = 14, to=30, by=2))

# Call the network topology analysis function

sftD = pickSoftThreshold(datExprD,
                         blockSize = 16386,
                         powerVector = powers,
                         networkType = "unsigned",
                         verbose = 5)

# Plot the results:
sizeGrWindow(9, 5)
par(mfrow = c(1,2));
cex1 = 0.9;

# Scale-free topology fit index as a function of the soft-thresholding power D
png("power_D_pearson_unsigned.png", width = 1600, height = 1200, units = "px", pointsize = 32, bg = "white");
plot(sftD$fitIndices[,1], -sign(sftD$fitIndices[,3])*sftD$fitIndices[,2],
xlab="Soft Threshold (power)",ylab="Scale Free Topology Model Fit,signed R^2",type="n",
main = paste("Scale independence (D)"));
text(sftD$fitIndices[,1], -sign(sftD$fitIndices[,3])*sftD$fitIndices[,2],
labels=powers,cex=cex1,col="red");

# this line corresponds to using an R^2 cut-off of h
abline(h=0.85,col="red")
dev.off()

# Scale-free topology connectivity
png("connectivity_D_pearson_unsigned.png", width = 1600, height = 1200, units = "px", pointsize = 32, bg = "white");
plot(sftD$fitIndices[,1], sftD$fitIndices[,5],
     xlab="Soft Threshold (power)",ylab="Mean Connectivity", type="n",
     main = paste("Mean connectivity (D)"))
text(sftD$fitIndices[,1], sftD$fitIndices[,5], labels=powers, cex=cex1, col="red")
dev.off()
```
