---
title: "Mean Connectivity for W data set"
author: "Ruben Sancho, Bruno Contreras Moreira"
output:
  html_document: default
  pdf_document: default
---

```{r knitr setup, include=FALSE,  eval=TRUE, echo=FALSE, warning=FALSE}
library(knitr)
knitr::opts_chunk$set(eval=TRUE, cache=FALSE, message=FALSE, warning=FALSE,
                      comment = "")
```


```{r connectivity}

# Display the current working directory
getwd();
workingDir = ".";
setwd(workingDir);


# Load the WGCNA package
workingDir = ".";
setwd(workingDir);
library(WGCNA);
options(stringsAsFactors = FALSE);
allowWGCNAThreads();

# Load data and networks
load(file = "net_W_unsigned.RData")
load(file = "adj_W.RData")


#Modules W:

#   0    1    2    3    4    5    6    7    8    9   10   11   12   13 
#9675 1866  870  827  701  607  435  390  288  282  246   89   62   48 


#      black        blue       brown       green greenyellow        grey 
#        390         870         827         607          89        9675 
#    magenta        pink      purple         red      salmon         tan 
#        282         288         246         435          48          62 
#  turquoise      yellow 
#       1866         701 


# INTRAMODULAR CONNECTIVITY:

kIM_W = intramodularConnectivity(adj_W, moduleColors_W, scaleByMax = F)


# 1 (turquoise)
which.color = "turquoise";
restrictGenes=moduleColors_W==which.color
kdiff_turquoise = kIM_W$kDiff[ restrictGenes]
mean_kdiff_turquoise = mean(kdiff_turquoise)
paste("mean kdiff 1 (turquoise)=", mean_kdiff_turquoise)

# 2 (blue)
which.color="blue";
restrictGenes=moduleColors_W==which.color
kdiff_blue = kIM_W$kDiff[ restrictGenes]
mean_kdiff_blue = mean(kdiff_blue)
paste("mean kdiff 2 (blue)=", mean_kdiff_blue)


# 3 (brown)
which.color="brown";
restrictGenes=moduleColors_W==which.color
kdiff_brown = kIM_W$kDiff[ restrictGenes]
mean_kdiff_brown = mean(kdiff_brown)
paste("mean kdiff 3 (brown)=", mean_kdiff_brown)

# 4 (yellow)
which.color="yellow";
restrictGenes=moduleColors_W==which.color
kdiff_yellow = kIM_W$kDiff[ restrictGenes]
mean_kdiff_yellow = mean(kdiff_yellow)
paste("mean kdiff 4 (yellow)=", mean_kdiff_yellow)

# 5 (green)

which.color="green";
restrictGenes=moduleColors_W==which.color
kdiff_green = kIM_W$kDiff[ restrictGenes]
mean_kdiff_green = mean(kdiff_green)
paste("mean kdiff 5 (green)=", mean_kdiff_green)

# 6 (red)

which.color="red";
restrictGenes=moduleColors_W==which.color
kdiff_red = kIM_W$kDiff[ restrictGenes]
mean_kdiff_red = mean(kdiff_red)
paste("mean kdiff 6 (red)=", mean_kdiff_red)

# 7 (black)

which.color="black";
restrictGenes=moduleColors_W==which.color
kdiff_black = kIM_W$kDiff[ restrictGenes]
mean_kdiff_black = mean(kdiff_black)
paste("mean kdiff 7 (black)=", mean_kdiff_black)

# 8 (pink)
which.color="pink";
restrictGenes=moduleColors_W==which.color
kdiff_pink = kIM_W$kDiff[ restrictGenes]
mean_kdiff_pink = mean(kdiff_pink)
paste("mean kdiff 8 (pink)=", mean_kdiff_pink)

# 9 (magenta)
which.color="magenta";
restrictGenes=moduleColors_W==which.color
kdiff_magenta = kIM_W$kDiff[ restrictGenes]
mean_kdiff_magenta = mean(kdiff_magenta)
paste("mean kdiff 9 (magenta)=", mean_kdiff_magenta)

# 10 (purple)
which.color="purple";
restrictGenes=moduleColors_W==which.color
kdiff_purple = kIM_W$kDiff[ restrictGenes]
mean_kdiff_purple = mean(kdiff_purple)
paste("mean kdiff 10 (purple)=", mean_kdiff_purple)

# 11 (greenyellow)
which.color="greenyellow";
restrictGenes=moduleColors_W==which.color
kdiff_greenyellow = kIM_W$kDiff[ restrictGenes]
mean_kdiff_greenyellow = mean(kdiff_greenyellow)
paste("mean kdiff 11 (greenyellow)=", mean_kdiff_greenyellow)

# 12 (tan)
which.color="tan";
restrictGenes=moduleColors_W==which.color
kdiff_tan = kIM_W$kDiff[ restrictGenes]
mean_kdiff_tan = mean(kdiff_tan)
paste("mean kdiff 12 (tan)=", mean_kdiff_tan)

# 13 (salmon)
which.color="salmon";
restrictGenes=moduleColors_W==which.color
kdiff_salmon = kIM_W$kDiff[ restrictGenes]
mean_kdiff_salmon = mean(kdiff_salmon)
paste("mean kdiff 13 (salmon)=", mean_kdiff_salmon)

```
