---
title: "Comparing unsigned consensus (Cons) vs drought (D) modules"
author: "Ruben Sancho, Bruno Contreras Moreira"
output:
  html_document: default
  pdf_document: default
---

```{r knitr setup, include=FALSE,  eval=TRUE, echo=FALSE, warning=FALSE}
library(knitr)
knitr::opts_chunk$set(eval=TRUE, cache=FALSE, message=FALSE, warning=FALSE, 
                      comment = "")
```

```{r load}

library(WGCNA);
options(stringsAsFactors = FALSE);
allowWGCNAThreads();

# Load the consensus data
lnames = load(file = "Consensus-dataInput.RData");

#The variable lnames contains the names of loaded variables.
lnames

# Load the results of consensus network
lnames = load(file = "Consensus-NetworkConstruction-auto.RData");
lnames

# Drought network
lnames = load("net_D_unsigned.RData")
lnames

# Rename variables to avoid conflicts
# netD, MEs_D, moduleLabels_D, moduleColors_D, geneTree_D,

moduleLabels_D;
moduleColors_D;
geneTree_D;
MEs_order_D = orderMEs(MEs_D, greyName = "ME0");

# Consensus net
lnames = load("Consensus-NetworkConstruction-auto.RData")
lnames
```

```{r pvalue}

# Isolate the module labels in the order they appear in ordered module eigengenes
D_ModuleLabels = substring(names(MEs_order_D), 3)
consModuleLabels = substring(names(consMEs[[1]]$data), 3)

# Convert the numeric module labels to color labels
D_Modules = labels2colors(as.numeric(D_ModuleLabels))
consModules = labels2colors(as.numeric(consModuleLabels))

# Numbers of female and consensus modules
nD_Mods = length(D_Modules)
nConsMods = length(consModules)

# Initialize tables of p-values and of the corresponding counts
pTable = matrix(0, nrow = nD_Mods, ncol = nConsMods);
CountTbl = matrix(0, nrow = nD_Mods, ncol = nConsMods);

# Execute all pairwaise comparisons
for (Dmod in 1:nD_Mods)
  for (cmod in 1:nConsMods)
  {
    D_Members = (moduleColors_D == D_Modules[Dmod]);
    consMembers = (moduleColors == consModules[cmod]);
    pTable[Dmod, cmod] = -log10(fisher.test(D_Members, consMembers, alternative = "greater")$p.value);
    CountTbl[Dmod, cmod] = sum(moduleColors_D == D_Modules[Dmod] & moduleColors ==
                      consModules[cmod])
  }
```

```{r plot}

# To display the p-value and count tables in an informative way, we create a color-coded table of the intersection counts.
# The colors will indicate the p-value significance

# Truncate p values smaller than 10^{-50} to 10^{-50} 
pTable[is.infinite(pTable)] = 1.3*max(pTable[is.finite(pTable)]);
pTable[pTable>50 ] = 50 ;

# Marginal counts (really module sizes)
D_ModTotals = apply(CountTbl, 1, sum)
consModTotals = apply(CountTbl, 2, sum)

# Actual plotting
sizeGrWindow(10,7 );
png("compare_modules_Consensus_vs_D.png", width = 2200, height = 2600, units = "px", pointsize = 22, bg = "white");
par(mfrow=c(1,1));
par(cex = 1.0);
par(mar=c(16, 16, 5, 3)+0.5);

# Use function labeledHeatmap to produce the color-coded table with all the trimmings
labeledHeatmap(Matrix = pTable,
               xLabels = paste(" ", consModules),
               yLabels = paste(" ", D_Modules),
               colorLabels = TRUE,
               xSymbols = paste("Cons ", consModules, ": ", consModTotals, sep=""),
               ySymbols = paste("D ", D_Modules, ": ", D_ModTotals, sep=""),
               textMatrix = CountTbl,
               colors = greenWhiteRed(100)[50:100],
               main = "Correspondence of Drought set-specific and Drought-Water consensus modules", 
               cex.main = 2.0, cex.text = 2.0, cex.lab = 2.0, setStdMargins = FALSE);
dev.off()

```
