---
title: "NetRep analysis"
author: "Ruben Sancho, Bruno Contreras Moreira"
output:
  html_document: default
  pdf_document: default
---

```{r knitr setup, include=FALSE,  eval=TRUE, echo=FALSE, warning=FALSE}
library(knitr)
knitr::opts_chunk$set(eval=TRUE, cache=FALSE, message=FALSE, warning=FALSE,
                      comment = "")
```

```{r NetRep}

workingDir = ".";
setwd(workingDir);
library("NetRep")

# Data
load(file = "datExpr.RData")
datExprD_matrix <- as.matrix(datExprD)
datExprW_matrix <- as.matrix(datExprW)
rownames(datExprD_matrix) <- paste("Discovery_",seq(1:nrow(datExprD_matrix)),sep="")
rownames(datExprW_matrix) <- paste("Test_",seq(1:nrow(datExprW_matrix)),sep="")

dim(datExprD)
dim(datExprW)

## discovery_data = dry
## test_data = water

# Pearson correlation

## D
cor_D = cor(datExprD, use = 'p')
save(cor_D, file = "cor_D.RData")
write.csv(cor_D, file = "cor_D.csv")

## W
cor_W = cor(datExprW, use = 'p')
save(cor_W, file = "cor_W.RData")
write.csv(cor_W, file = "cor_W.csv")

dim(cor_D)
dim(cor_W)

#the correlation-coefficients between each pair of genes
load(file = "adj_D.RData")
load(file = "adj_W.RData")

dim(adj_D)
dim(adj_W)


load(file = "net_D_unsigned.RData")
labels_list <- netD$colors
names(labels_list) <- names(datExprD)

data_list <- list(discovery=datExprD_matrix, test=datExprW_matrix)
correlation_list <- list(discovery=cor_D, test=cor_W)
network_list <- list(discovery=adj_D, test=adj_W)



# We will use NetRep to permutation test whether the network topology of each module is preserved in our test dataset (WATER) using the modulePreservation function
# For RNA-seq --> null = "all"

#Preservation dry vs water
preservation <- modulePreservation(network=network_list, data=data_list, correlation=correlation_list, 
moduleAssignments=labels_list, discovery="discovery", test="test", nPerm=10000, null = "all", nThreads=10)

save(preservation, file = "NetRep.RData")

# We will consider all statistics equally important, so we will consider a module to be preserved in cohort2 if all the statistics have a permutation test P-value < 0.01.
# Get the maximum permutation test p-value
max_pval <- apply(preservation$p.value, 1, max)
max_pval

# check each statistics
load(file = "NetRep.RData")
preservation$p.value

```
